/** @module enemyLearning.config
 * Cross-run enemy adaptation settings.
 *
 * The learning model is intentionally tiny and browser-native so the game
 * stays dependency-light and deterministic across runs. */

import { GAME_CONFIG } from './game.config.js';

export const ENEMY_LEARNING_CONFIG = Object.freeze({
  storageKey: 'warp-nemesis.enemyLearning',
  datasetStorageKey: 'warp-nemesis.enemyLearning.dataset',
  squadStorageKey: 'warp-nemesis.enemyLearning.squad',
  squadDatasetStorageKey: 'warp-nemesis.enemyLearning.squadDataset',
  featureVersion: 8,
  sampleIntervalMs: 250,
  heartbeatSampleIntervalMs: 1000,
  decisionSampleDebounceMs: 120,
  maxSamplesPerEnemy: 40,
  maxExamplesPerEnemyType: 480,
  maxSquadExamples: 1800,
  recentTelemetryLevels: 3,
  learningRate: 0.18,
  regularization: 0.0005,
  trainingEpochsPerRun: 6,
  squadTrainingEpochsPerRun: 8,
  squadLearningRate: 0.12,
  squadRegularization: 0.0008,
  squadHiddenUnits: 12,
  level2Number: 2,
  minTrainingSpawns: 1,
  exposureFloor: 0.2,
  runtimeWeights: Object.freeze({
    win: 0.55,
    survival: 0.45,
    pressure: 0.35,
    collision: 1.10,
    bullet: 1.20,
    spacing: 0.45,
    laneCrowding: 0.25,
    corner: 0.18,
  }),
  runtimePolicy: Object.freeze({
    positionOffsets: Object.freeze([-1, -0.5, 0, 0.5, 1]),
    verticalOffsets: Object.freeze([-1, -0.5, 0, 0.5, 1]),
    speedScalars: Object.freeze([0, 0.5, 1]),
    sameTypeSpacingPx: 88,
    laneCrowdingPx: 72,
    cornerPenaltyDistancePx: 112,
    adaptiveFireScoreFloor: 0.22,
    adaptivePressureFloor: 0.42,
    adaptiveWinFloor: 0.48,
    adaptiveForceFireMultiplier: 2.1,
  }),
  squadRuntimePolicy: Object.freeze({
    cadenceFloor: 0.8,
    cadenceCeil: 1.35,
    spreadFloor: 0.9,
    spreadCeil: 1.6,
    driftFloor: 0.9,
    driftCeil: 1.45,
    verticalBiasMinPx: -26,
    verticalBiasMaxPx: 34,
    aggressivePattern: 'wings',
    cautiousPattern: 'alternating_rows',
  }),
  levelTransitionTraining: Object.freeze({
    currentRunExtraWeight: 2,
  }),
  neuralDance: Object.freeze({
    storageKey:                'warp-nemesis.danceWaypoint',
    minSamplesForActivation:   40,
    survivalFloor:             0.55,
    pressureFloor:             0.25,
    hiddenUnits:               16,
    learningRate:              0.08,
    regularization:            0.001,
    epochs:                    10,
    temperatureInitial:        2.0,
    temperatureFinal:          0.7,
    temperatureSampleConverge: 200,
    modeHysteresisThreshold:   0.15,
    maxPhrasesBeforeExit:      8,
    phraseTiming: Object.freeze({
      hold:    Object.freeze({ durationMs: 500, holdMs: 400 }),
      press:   Object.freeze({ durationMs: 750, holdMs: 250 }),
      flank:   Object.freeze({ durationMs: 850, holdMs: 150 }),
      evade:   Object.freeze({ durationMs: 300, holdMs: 100 }),
      retreat: Object.freeze({ durationMs: 600, holdMs: 450 }),
    }),
  }),
  labeling: Object.freeze({
    outcomeHorizonMs: 750,
    minSurvivalObservationMs: 500,
    strongOutcomeMagnitudeThreshold: 0.35,
    weakOutcomeMagnitudeThreshold: 0.15,
    heartbeatDropThreshold: 0.25,
  }),
  normalization: Object.freeze({
    width: GAME_CONFIG.WIDTH,
    height: GAME_CONFIG.HEIGHT,
    diagonal: Math.hypot(GAME_CONFIG.WIDTH, GAME_CONFIG.HEIGHT),
    maxSpeed: 400,
    maxLifetimeMs: 15000,
    maxSpawns: 40,
    maxShotsPerSpawn: 8,
    maxHpDamagePerSpawn: GAME_CONFIG.PLAYER_HP_MAX,
    maxShieldDamagePerSpawn: Math.max(1, GAME_CONFIG.PLAYER_SHIELD_MAX),
    maxCollisionDeathsPerSpawn: 1,
    maxShotsPerSquad: 32,
    maxHpDamagePerSquad: GAME_CONFIG.PLAYER_HP_MAX,
    maxShieldDamagePerSquad: Math.max(1, GAME_CONFIG.PLAYER_SHIELD_MAX),
    maxBulletThreatDistance: Math.hypot(GAME_CONFIG.WIDTH, GAME_CONFIG.HEIGHT),
    maxBulletTimeToImpactMs: 1500,
    maxPrimaryDamageMultiplier: 4,
    sameLaneThresholdPx: 56,
  }),
});
